dist: bionic
language: java
addons:
  sonarcloud:
    organization: "vvator-github"
    token:
      secure: "8310d4c46801913d498520c3b7005afa3535575b" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean install sonar:sonar -Dsonar.projectKey=VVATOR_waybills
  - mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=vvator-github -Dsonar.login=e6165af87334737fa0ceef25a2bf8bf0194a0d01
branches:
  only:
    - master
    - stable
deploy:
  - provider: heroku
    api-key:
      secure: $HEROKU_API_KEY
    app: waybill-service
    file_glob: true
    file:
      - Procfile
      - waybill-root/waybill-service/target/waybill-service.jar
    on:
      branch: master
  - provider: heroku
    api-key:
      secure: $HEROKU_API_KEY
    app: waybill-service-dev
    file_glob: true
    file:
      - Procfile
      - waybill-root/waybill-service/target/waybill-service.jar
    on:
      branch: develop

