dist: bionic
language: java
deploy:
  file_glob: true
  file:
    - Procfile
    - waybill-service/target/waybill-service.jar
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: waybill-service
